# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
chol_update <- function(LL, xx) {
    .Call('mixtureModels_chol_update', PACKAGE = 'mixtureModels', LL, xx)
}

#' @export
chol_downdate <- function(LL, xx) {
    .Call('mixtureModels_chol_downdate', PACKAGE = 'mixtureModels', LL, xx)
}

calculate_log_V_n <- function(alpha, N, how_many) {
    .Call('mixtureModels_calculate_log_V_n', PACKAGE = 'mixtureModels', alpha, N, how_many)
}

